### PR TITLE
use gh to compare Github branch configuration

### PR DESCRIPTION
**Pull request by goneri**
Use the `gh` CLI tool to query Github API to get the right default branch. Use this information to compare wit the local  configuration.

Also properly compare the name of the repository, ansible-community/molecule is in github.com/ansible-community/molecule-libvirt but are not the same.
    
Finally use an emoji to mark the sections instead of a series of '='. Those where getting too long.

### CODE REVIEW

**Comment by pabelanger** [comment]
what is gh tool? Where do we install it from?

**Comment by goneri** [comment]
> what is gh tool? Where do we install it from?

It's github's official CLI: https://github.com/cli/cli

I took this approach to avoid sharing a secret. We can later drop the the gh dependency and call the API directly.

**Comment by pabelanger** [comment]
Does gh require a token or can it pull this info anonymously?

**Comment by goneri** [comment]
> Does gh require a token or can it pull this info anonymously?

It does, and it handles that for the user pretty well.

**Comment by pabelanger** [comment]
Ack, thanks. So you plan on adding the token to query github? I don't see it here and mostly trying to understand how this logic will be used.

**Comment by goneri** [comment]
gh stores the token in its configuration. So I just assume this has already be done before we call the test script. I don't plan to integrate this in the CI for now. This feature will only work locally for now.

**Comment by pabelanger** [comment]
Okay, I'm not sure who is expect to run this logic.  Given ansible/project-config is a trusted repo, can create a secret for the job.

can you share the output of the command?

**Comment by goneri** [comment]
I did this block initially just to validate https://github.com/ansible/project-config/pull/930. The result already useful for me and any gh users. The day we decide to run the function in the CI, we will just need to generate an oauth token somehow.

```
$ gh repo view ansible-community/molecule --json defaultBranchRef --jq .defaultBranchRef.name
main
```

**Pull request merged**
