### PR TITLE
add ansible/cloud-ee project

### PR DESCRIPTION
**Pull request by goneri**
`ansible/cloud-ee` is the Execution Environment for the Ansible Cloud
Collections.

### CODE REVIEW

**Comment by dmsimard** [comment]
@goneri sorry for noticing this just now. Is this PR still relevant ? I see that https://github.com/ansible/cloud-ee is empty.

Your PR failed CI because the project needs to be added to the tenants file first: https://github.com/ansible/project-config/blob/master/zuul/tenants.yaml

**Comment by goneri** [comment]
> @goneri sorry for noticing this just now. Is this PR still relevant ? I see that https://github.com/ansible/cloud-ee is empty.
> 
> Your PR failed CI because the project needs to be added to the tenants file first: https://github.com/ansible/project-config/blob/master/zuul/tenants.yaml

Thanks David.

This way a low priority thing. I actually opened the PR before the cloud-ee repository was created.

**Comment by pabelanger** [comment]
This fix here, was to remove jobs first. Then we can properly create the github repo, and setup branch protections.

We should expand the docs on https://github.com/ansible/project-config to include updates to github/projects.yaml and github/acls folder too.

**Comment by goneri** [comment]
recheck

**Comment by pabelanger** [comment]
> Build failed (promote pipeline). For information on how to proceed, see
> http://docs.openstack.org/infra/manual/developers.html#automated-testing
> 
> * [project-config-github-promote ](https://dashboard.zuul.ansible.com/t/ansible/build/80cc3b054ccd4bbaa32a937b1409fe1e) : FAILURE in 2m 25s

@goneri this is failing as my user needs to be admin on the repo.  We should change that to be ansible-zuul or some other 'admin' account.

**Comment by goneri** [comment]
ok, thanks for the help Paul. I fixed that.

**Comment by pabelanger** [comment]
sadly, we need a new PR to touch github/project.yaml for the job to run again. And setup the permissions properly.

**Comment by goneri** [comment]
> sadly, we need a new PR to touch github/project.yaml for the job to run again. And setup the permissions properly.

NP, here we go: https://github.com/ansible/project-config/pull/719

**Pull request merged**
