### PR TITLE
rename the vmware projects

### PR DESCRIPTION
**Pull request by goneri**
Depends-On: https://github.com/ansible/project-config/pull/614

- `vmware` becomes `community.vmware`
- `vmware_rest` becomes `vmware.vmware_rest`

Closes: ansible-collections/vmware#151
Closes: ansible-collections/vmware_rest#18

### CODE REVIEW

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by mariolenz** [comment]
@goneri Why did you rename `https://github.com/ansible-collections/vmware` to `https://github.com/ansible-collections/community.vmware`, but `https://github.com/ansible-collections/vmware_rest` to `https://github.com/ansible-collections/vmware.vmware_rest`?

`vmware_rest` is a community collection, so I think it should be in the community namespace. IANAL, but it might be legally problematic to claim the `vmware` namespace when you're not acting for VMware.

Anyway, this namepace suggests that that it's kind of an official collection from VMware. If the modules work, it looks like they did a good job. If they don't, they can say these modules are from the community and they can't do anything about it. VMware can only win while you can only loose imho.

**Pull request merged**
