### PR TITLE
Retarget AWS collections to branch `main`

### PR DESCRIPTION
**Pull request by jillr**

### CODE REVIEW

**Comment by pabelanger** [comment]
@jillr do you also want to create / manage branch protection too?  See: https://github.com/ansible/project-config/blob/master/github/acls/ansible-collections/symantec.epm.config for example

**Comment by jillr** [comment]
@pabelanger since I'm split across shippable and zuul, just to confirm - what that does in effect is say that unless an admin smashes override merging is blocked unless whatever configured zuul checks exist (in my case, the release checks) pass?  Is that correct?

**Comment by pabelanger** [comment]
So because we don't gate code (hopefuly yet) on these collections, you likely could use the following
```
---
# NOTE(pabelanger): See https://developer.github.com/v3/repos/branches/#parameters-1
# for fields
- branch:
  name: main 
  enforce_admins: true
```

The main win, here is we make all the updates to github in one pass. But, given we haven't discussed governance on repos in general, I feel it is up to you if you want to do it or not.

**Comment by jillr** [comment]
I see no reason not to get into the system, as it were, for managing acls, project settings, etc.

**Comment by pabelanger** [comment]
lets see how it works :)

**Pull request merged**
