### PR TITLE
Added 'servicenow.itsm' in projects

### PR DESCRIPTION
**Pull request by Akasurde**
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

### CODE REVIEW

**Comment by Akasurde** [comment]
cc @goneri

**Comment by goneri** [comment]
Can you also add these files: https://github.com/ansible/project-config/pull/718

**Comment by Akasurde** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
@pabelanger Zuul configuration has not been updated follow up to the merge of https://github.com/ansible/project-config/pull/786 https://dashboard.zuul.ansible.com/t/ansible/builds?job_name=windmill-config-deploy

**Comment by goneri** [comment]
```2021-04-01 15:01:30.113180 | bastion02.ca-ymq-1.vexxhost.zuul.ansible.com | An exception occurred during task execution. To see the full traceback, use -vvv. The error was:     _os.mkdir(file, 0o700)
2021-04-01 15:01:30.114543 | bastion02.ca-ymq-1.vexxhost.zuul.ansible.com | fatal: [nb01.sjc1.vexxhost.zuul.ansible.com]: FAILED! =>
2021-04-01 15:01:30.114572 | bastion02.ca-ymq-1.vexxhost.zuul.ansible.com |   msg: Unexpected failure during module execution.
2021-04-01 15:01:30.114591 | bastion02.ca-ymq-1.vexxhost.zuul.ansible.com |   stdout: ''
```

**Comment by goneri** [comment]
nb01 FS is full. I'm removing some large files.

**Comment by goneri** [comment]
@GomathiselviS ^, this may impact your works.

**Comment by pabelanger** [comment]
There shouldn't be a need to manually remove files, if the FS is full there is likely something wrong with nodepool-builder. In this case, there was a stuck zk record, that was stopping nodepool-builder from deleting images in the openstack providers.

Likely some sort of bug. I have unblocked it, and nodepool-builder has now cleaned up properly.

**Pull request merged**
