### PR TITLE
github-3pci: accept .zuul.d configuration

### PR DESCRIPTION
**Pull request by goneri**

### CODE REVIEW

**Comment by goneri** [comment]
@Akasurde would like to maintain a `.zuul.d/` directory within `community.okd`. @pabelanger, am I doing the right thing?

**Comment by goneri** [comment]
C.f: https://github.com/openshift/community.okd/pull/128

**Comment by pabelanger** [comment]
@goneri I wouldn't accept this on 3pci, as there is a chance they could break zuul configuration.  And if that happens, it makes is more difficult to remove the broken jobs.

The better solution would be to move them into their own tenant for some isolation, for now they could add the changes in ansible-zuul-jobs / project-config

**Comment by goneri** [comment]
My understanding is that the configuration coming from the repository .zuul.d will only be loaded for its jobs. If so, the risk sounds pretty limited. Am I understand this wrongly?

**Comment by pabelanger** [comment]
> My understanding is that the configuration coming from the repository .zuul.d will only be loaded for its jobs. If so, the risk sounds pretty limited. Am I understand this wrongly?

no, it is all configuration pipelines / projects / jobs, etc. The main issue is, if they land bad zuul configuration and go to reload zuul or restart zuul and cannot parse the configuration properly, we are in a broken state.  And because this repo is outside of our admin control, we have limited scope to force merge fixes.

To me, the risk is large enough to not enable in the ansible tenant but create a new tenant for them if they would like it. Otherwise, project-config / ansible-zuul-jobs would be my recommendation right now

**Comment by goneri** [comment]
> > My understanding is that the configuration coming from the repository .zuul.d will only be loaded for its jobs. If so, the risk sounds pretty limited. Am I understand this wrongly?
> 
> no, it is all configuration pipelines / projects / jobs, etc. The main issue is, if they land bad zuul configuration and go to reload zuul or restart zuul and cannot parse the configuration properly, we are in a broken state. And because this repo is outside of our admin control, we have limited scope to force merge fixes.
> 
> To me, the risk is large enough to not enable in the ansible tenant but create a new tenant for them if they would like it. Otherwise, project-config / ansible-zuul-jobs would be my recommendation right now

Wow, thank you for the explanation. I totally understand your position now.

**Pull request closed without merging**
