### PR TITLE
ciscosmb project

### PR DESCRIPTION
**Pull request by Andersson007**

### CODE REVIEW

**Comment by Andersson007** [comment]
relates to https://github.com/ansible/project-config/pull/837

**Comment by Andersson007** [comment]
https://github.com/ansible-collections/community.ciscosmb/issues/25#issuecomment-853000054

**Comment by Andersson007** [comment]
recheck

**Comment by Andersson007** [comment]
@pabelanger i put `recheck` and tried close-open the PR but the tests don't want to relaunch

**Comment by pabelanger** [comment]
you need to wait until your other PR has been promoted, so zuul knows about the project config. You can see the error returned by zuul: https://dashboard.zuul.ansible.com/t/ansible/buildset/e9bbd850690b4a3a9278ff368a200b4f

**Comment by pabelanger** [comment]
recheck

**Comment by Andersson007** [comment]
@pabelanger cool, thanks for the clarification, will know

**Comment by Andersson007** [comment]
the checks have passed, we can label it now

**Pull request merged**
